### ISSUE TITLE
how to communicate two fpga(xilinx) boards together using I2C? please provide code and other details

### ISSUE THREAD

**Issue by sagar11101997** [oetr/FPGA-I2C-Worker#1]
we have to make one fpga as master , another one as slave and through i2c , we have to communicate them with each other

**Comment by oetr** [comment]
Then you should write the circuit for the I2C master.

But if you have two FPGA boards, why not connect them directly and have async buffers/FIFOs on both ends? I2C sets a hard limit on how fast you can get your data from one board to the other.
Hope that helps
Peter

**Comment by sagar11101997** [comment]
We need I2C protocol Only as multiple FPGA Needs to be connected to one
masterboard.
Can you please provide the code.

**Comment by oetr** [comment]
Sorry, I don't have the code for the I2C master.
