### ISSUE TITLE
respond to multiple address question

### ISSUE THREAD

**Issue by mhanuel26** [oetr/FPGA-I2C-Worker#3]
Hi,

Just wondering if this slave can respond to different addresses?

Also, have you tried this on any hardware?

Thanks,

**Comment by oetr** [comment]
To set the slave address use the generic when instantiating:
 ```
generic map (
      MINION_ADDR          => "0000011",
      ...
```
The module was tested on a Spartan3-Board talking to a µC some time ago.

**Comment by mhanuel26** [comment]
Hi @oetr ,

Just to confirm, can I have more than one MINION_ADDR ?

If so, how can I specify different address space for the slaves?

Thanks,

**Comment by oetr** [comment]
Each slave has its own unique address on the bus. If you want a slave to answer to a range of addresses, you will have to modify the code.
